### PR TITLE
add mesos https support

### PR DESCRIPTION
**Pull request by vixns**

### CODE REVIEW

**Comment by clems4ever** [comment]
Nice one! I'll try to help you with the tests soon.

**Comment by clems4ever** [comment]
@vixns , thank you in the meantime.

**Comment by clems4ever** [comment]
I'm closing this PR in favor of #6

**Comment by kamaradclimber** [comment]
What should we do with that PR?

**Comment by clems4ever** [comment]
Closing the PR in favor of #19

**Pull request closed without merging**
